### ISSUE TITLE
How translations work in forms

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#409]
How to provide multilanguage custom validation messages in form configuration

```yml
customizations:
  expertise:
    validation:
      presence:
        message: record is required.
```

```yml
rate_amount:
  validation:
    presence: true
    numericality:
      greater_than_or_equal_to: 0
```
