### ISSUE TITLE
Update /users/creating-user-property

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#928]
default.yml is just a UserProfileScchema with name “default”, it’s placed in user_profile_scchemas directory, in form you have to do

```
resource: User
fields:
  profiles:
    default: 
      properties:
        my_property:
```
 
and then in graphql you need to fetch values via profiles, whee’as user.yml is placed in app and it’s like adding property directly to user:

```
resource: User
fields:
  properties:
    my_property:
```
and then in graphql you fetch it also directly from user [ same as with models, no need to go through extra step of user profile.

At the end of the day, both approaches work and both have advantages and disadvantages. I find user.yml much easier to use, but it lacks namespace and you can’t add user property via module [ as this could generate tons of collisions ]
